# Generated by Django 4.2.7 on 2023-11-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
    ]
